spring:
  application:
    name: blog
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blogtestdb
    initialize: true
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  issuer: 44goodluck44@gmail.com
  secret_key: blog-springbbot
#  http://localhost:8080/h2-console